"""Emit zoomy_core's march constants into a C++ header (mandate 6a).

The user law: **no numerical constant is hard-coded in a backend**.  Foam had
inherited a MOOD dead band ``h < -1.0e-10`` verbatim from the dmplex port,
while core (``solver_numpy.py``) and amrex (``ZoomyAmr.cpp``, ``!(h >= 0.0)``)
detect on strict zero.  Core now RESOLVES that bound as an emitted constant
(``zoomy_core.solver.constants.march_constants``), so foam reads it from there
instead of restating a number.

SCOPE, stated plainly: only the MOOD pair is emitted today.  ``march_constants``
also resolves ``c_cfl`` / ``c_kp_eps`` / ``c_eps_h`` / ``c_dt_max``, and those
sites in ``numerics.H`` are still literal — that is a REPORTED remainder of
mandate 6a on this backend, not a claim that it is finished here.

The generated header is the ONE place a float literal is allowed to appear:
it is the ``constexpr`` that DEFINES the named value, which is exactly what
"the constants are emitted" means.  Every comparison site uses the name.
"""
from __future__ import annotations

from pathlib import Path

#: The constants this backend actually consumes.  Kept explicit so a name that
#: core stops emitting fails loudly here rather than silently vanishing from
#: the header and leaving a C++ compile error as the only symptom.
CONSUMED = ("c_mood_h_bound", "c_mood_require_finite")

_CTYPE = {"c_mood_h_bound": "Foam::scalar", "c_mood_require_finite": "int"}


def march_constants_for(nsm, *, cfl: float = 0.9, dimension: int = 1,
                        degree: int = 1):
    """Resolve core's march constants for ``nsm``.  Thin, deliberate wrapper:
    the resolution logic lives in core and is never re-implemented here."""
    from zoomy_core.solver.constants import march_constants

    return march_constants(nsm, cfl=cfl, dimension=dimension, degree=degree)


def render(consts) -> str:
    """Render the consumed constants as a ``namespace Model`` header."""
    lines = [
        "#pragma once",
        "// GENERATED by zoomy_foam/_constants.py from",
        "// zoomy_core.solver.constants.march_constants — DO NOT EDIT.",
        "//",
        "// Mandate 6a: the backend compares against these NAMES, never against a",
        "// literal.  The literals below are the defining assignments.",
        "namespace Model {",
    ]
    for name in CONSUMED:
        if name not in consts.values:
            raise KeyError(
                f"zoomy_core no longer emits {name!r}; zoomy_foam consumes it "
                f"(have: {sorted(consts.values)})")
        v = consts.values[name]
        if v is None:
            raise ValueError(
                f"{name!r} resolved to None ({consts.provenance[name]}) — "
                "foam's MOOD predicate has no build flag to guard it")
        ctype = _CTYPE[name]
        rendered = repr(float(v)) if ctype == "Foam::scalar" else str(int(v))
        lines.append(f"    // {name}: {consts.provenance[name]}")
        lines.append(f"    constexpr {ctype} {name} = {rendered};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_march_constants(nsm, out: Path, **kw) -> Path:
    """Emit ``MarchConstants.H`` next to the other generated headers."""
    out = Path(out)
    out.write_text(render(march_constants_for(nsm, **kw)))
    return out
